#version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sistem_inventaris_gudang_pt_rizky_badai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - vendor:/var/www/vendor
    working_dir: /var/www
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:24
    container_name: sistem_inventaris_gudang_pt_rizky_badai_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: mysql:8.4
    container_name: sistem_inventaris_gudang_pt_rizky_badai_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistem_inventaris_gudang_pt_rizky_badai_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: uprakkik
      MYSQL_PASSWORD: uprakkik
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: sistem_inventaris_gudang_pt_rizky_badai_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  node_modules:
  vendor:
  redisdata:
